# Generated by Django 5.0.2 on 2024-02-15 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_data', models.CharField(max_length=50)),
                ('int_data', models.IntegerField()),
                ('reg_data', models.DateTimeField(auto_now_add=True)),
                ('upd_data', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '입력데이터',
                'verbose_name_plural': '입력데이터들',
                'db_table': 'data_tbl',
            },
        ),
    ]
